### ISSUE TITLE
No support to .NetCore

### ISSUE THREAD

**Issue by Xamarians** [campaignmonitor/createsend-dotnet#53] opened 2017-10-26 07:48 UTC
I'd tried to install it in .Net Core Web Api but seems it doesn't support it. Is there any way to use this library in .NET Core?

**Comment by JanKolk** [comment] 2018-01-29 11:57
@Xamarians Are you using .netcore 2.0? I created a pull request thats supports 2.0 (#55)

**Comment by nblumhardt** [comment] 2018-01-31 23:26
Dupe of #41. Great to see a PR up, @JanKolk!!! :-)

**Comment by JanKolk** [comment] 2018-02-02 12:21
@nblumhardt I released a version to [nuget](https://www.nuget.org/packages/campaignmonitor-api-dotnet-standard) until the pull request is merged.

**Comment by mattgenious** [comment] 2019-09-11 09:03
Hello @niawahyuni can we please have official support for .net standard 2.0?

**Comment by edgunn** [comment] 2019-10-03 04:04
.NET Standard 2.0 is now officially supported as of v5.2.0, apologies for the far too long delay!
Any issues please let me know

**Closed by edgunn** 2019-10-03 04:04 UTC
